### ISSUE TITLE
Undead Legacy 2.6.12 Compatibility

### ISSUE THREAD

**Issue by kaliber64** [Westwud1/QuickStack#7]
Hotkeys result in Null Reference. I'd love to use this mod in Undead Legacy if possible.

**Comment by Ardyey** [comment]
+1 for Undead Legacy compatibility. Although I won't get my hopes up since UL changes the core game too much.

**Comment by Westwud1** [comment]
Tried to fix it a quite a while ago without much success. Like @Ardyey said, the mod changes the core game a lot. Maybe with 1.6.0 config hotkey rebinding you could change the hotkeys to something else that might work (haven't tested it).

**Comment by michaelarlt** [comment]
![image](https://github.com/Westwud1/QuickStack/assets/18514062/030fca9e-7f0b-47b3-a0eb-d6f72081c3c2)
Won't parse the config which i changed to
`<configs>
	<append xpath="/windows/window[@name='windowBackpack']/rect/rect/grid[@size='216,36']">
			<button depth="3" name="btnMoveQuickRestock" sprite="ui_game_symbol_quickrestock" tooltip_key="lblStashQuickRestock" pos="0, 0" style="icon32px, press, hover" pivot="center" sound="[paging_click]"/>
			<button depth="3" name="btnMoveQuickStack" sprite="ui_game_symbol_quickstack" tooltip_key="lblStashQuickStack" pos="0, 0" style="icon32px, press, hover" pivot="center" sound="[paging_click]"/>
	</append>
</configs>`
just to test. Buttons are there (even if badly placed) and do click but nothing happens. Probably because of the dll not applying. OCB modlets do work fine tho.
QuickStack Version: 1.6.3
